/* Portable, local-only notebook backups. Validate before changing stored records. */
window.NotebookData=(()=>{
 const species=['鸟','猫','狗','兔子','仓鼠','鱼','其他'];
 const fail=()=>{throw Error('备份内容不完整或格式不正确，现有记录不会更改。')};
 const text=(v,max,required=false)=>{if(v==null&&!required)return '';if(typeof v!=='string'||v.length>max||(required&&!v.trim()))fail();return v};
 const image=v=>{if(!v)return '';if(typeof v!=='string'||v.length>5000000||!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(v))fail();return v};
 const num=(v,min,max)=>{if(!Number.isFinite(v)||v<min||v>max)fail();return v};
 function planet(p){if(p==null)return undefined;if(p.format!=='among-stars-planet'||p.version!==1||!['meadow','woodland','lake'].includes(p.template)||!Array.isArray(p.cells)||p.cells.length!==32||!Array.isArray(p.items)||p.items.length>24)fail();const integers=(v,a,b)=>{num(v,a,b);if(!Number.isInteger(v))fail();return v};const result={format:p.format,version:1,name:text(p.name,24),seed:integers(p.seed,0,4294967295),template:p.template,palette:integers(p.palette,0,2),caption:text(p.caption,160),photo:image(p.photo)||null,originalPhoto:image(p.originalPhoto)||null,cells:p.cells.map(c=>({x:num(c.x,-1,1),y:num(c.y,-1,1),z:num(c.z,0,1),type:integers(c.type,0,5),variant:integers(c.variant,0,1)})),items:p.items.map(i=>({id:text(i.id,160,true),type:integers(i.type,0,7),x:num(i.x,-1,1),y:num(i.y,-1,1),scale:num(i.scale,.65,1.45),angle:num(i.angle,-25,25)}))};if(new Set(result.items.map(i=>i.id)).size!==result.items.length)fail();if(result.items.some(i=>Math.hypot(i.x,i.y)>.951))fail();const ring=p.ring||{type:'none',color:'#dec58f',angle:-18,width:18};if(!['none','line','crayon','dust'].includes(ring.type)||!/^#[a-fA-F0-9]{6}$/.test(ring.color))fail();result.ring={type:ring.type,color:ring.color,angle:num(ring.angle,-45,45),width:num(ring.width,5,38)};return result;}
 function record(r){if(!r||typeof r!=='object'||Array.isArray(r)||!species.includes(r.species))fail();const result={id:text(r.id,160,true),name:text(r.name,40,true),species:r.species,breed:text(r.breed,80),memory:text(r.memory,6000),words:text(r.words,6000),createdAt:text(r.createdAt,80),skyIndex:Number.isInteger(r.skyIndex)?num(r.skyIndex,0,19):0,pointIndex:Number.isInteger(r.pointIndex)?num(r.pointIndex,0,13):0,avatar:image(r.avatar),originalPhoto:image(r.originalPhoto),found:r.found===true};if(r.planet)result.planet=planet(r.planet);if(r.planetPreview)result.planetPreview=image(r.planetPreview);if(r.letters!==undefined){if(!Array.isArray(r.letters)||r.letters.length>1000)fail();result.letters=r.letters.map(l=>({id:text(l.id,160,true),text:text(l.text,6000),date:text(l.date,80),photo:image(l.photo)}));if(new Set(result.letters.map(l=>l.id)).size!==result.letters.length)fail()}return result;}
 function records(list){if(!Array.isArray(list)||list.length>200)fail();const clean=list.map(record);if(new Set(clean.map(r=>r.id)).size!==clean.length)fail();return clean;}
 function encounter(e){if(!e||typeof e!=='object'||Array.isArray(e))fail();const visitCount=num(e.visitCount,1,1000000);if(!Number.isInteger(visitCount))fail();const firstSeenAt=text(e.firstSeenAt,80,true),lastSeenAt=text(e.lastSeenAt,80,true);if(!Number.isFinite(Date.parse(firstSeenAt))||!Number.isFinite(Date.parse(lastSeenAt)))fail();return {recordId:text(e.recordId,160,true),firstSeenAt,lastSeenAt,visitCount}}
 function encounters(list){if(list===undefined)return[];if(!Array.isArray(list)||list.length>200)fail();const clean=list.map(encounter);if(new Set(clean.map(e=>e.recordId)).size!==clean.length)fail();return clean}
 function exportNotebook(list,seen=[]){return {format:'among-stars-notebook',version:1,exportedAt:new Date().toISOString(),records:records(list),encounters:encounters(seen)}}
 function exportRecords(list){return exportNotebook(list)}
 function parseNotebook(raw){let data;try{data=JSON.parse(raw)}catch{fail()}if(data?.format!=='among-stars-notebook'||data.version!==1)throw Error('请选择「完整观星手册」备份。单颗星球作品文件请在工作室打开。');return {records:records(data.records),encounters:encounters(data.encounters)}}
 function parseBackup(raw){return parseNotebook(raw).records}
 function mergeRecords(existing,incoming){const out=records(existing),valid=records(incoming);for(const r of valid){const match=out.find(x=>x.id===r.id);if(!match)out.push(r);else if(JSON.stringify(match)!==JSON.stringify(r)){let id;do{id='restored-'+crypto.randomUUID()}while(out.some(x=>x.id===id));out.push({...r,id})}}if(out.length>200)throw Error('恢复后超过200颗星球，请分开保管备份。');return out;}
 function mergeEncounters(existing,incoming){const out=encounters(existing);for(const item of encounters(incoming)){const match=out.find(e=>e.recordId===item.recordId);if(!match)out.push(item);else{match.firstSeenAt=Date.parse(match.firstSeenAt)<=Date.parse(item.firstSeenAt)?match.firstSeenAt:item.firstSeenAt;match.lastSeenAt=Date.parse(match.lastSeenAt)>=Date.parse(item.lastSeenAt)?match.lastSeenAt:item.lastSeenAt;match.visitCount=Math.max(match.visitCount,item.visitCount)}}return out}
 return {exportNotebook,exportRecords,parseNotebook,parseBackup,mergeRecords,mergeEncounters};
})();
