(() => {
'use strict';
const $=id=>document.getElementById(id), canvas=$('world-canvas'), ctx=canvas.getContext('2d');
const params=new URLSearchParams(location.search);let petId=params.get('pet');const creating=params.get('create')==='1';let flowStep=params.get('step')==='sticker'?3:2;let creation;try{creation=JSON.parse(localStorage.getItem('among-stars-creation-v2')||'null')}catch{};if(petId){const back=document.querySelector('.brand');back.href='./?pet='+encodeURIComponent(petId)+'&view=journal';back.setAttribute('aria-label','返回观星手册');}
const W=900,CX=450,CY=525,R=276,RES=560,STORE='among-stars-studio-v1';
const makeState=(...args)=>CollagePlanet.makeState(...args),makeCells=(...args)=>CollagePlanet.makeCells(...args);
const materials=['草地','林地','花园','泥土','岩石','水面'];
const objects=['树','花丛','石块','秋千','爬架','小屋','纸箱','照片贴纸'];
const sizes=[210,83,90,170,160,180,100,124];
const schemes=[
 {name:'苔绿',chips:['#66735a','#b5b786','#6a8b98'],tones:[[58,77,53],[152,162,103],[227,220,173]],water:[[31,66,80],[93,139,153],[200,213,206]]},
 {name:'橘海',chips:['#e8853c','#167f88','#fff1d6'],tones:[[126,54,38],[232,128,57],[255,241,214]],water:[[12,62,82],[22,135,145],[190,235,223]]},
 {name:'蓝夜',chips:['#f4f4e9','#152e68','#8ecdeb'],tones:[[16,32,76],[59,100,165],[247,245,229]],water:[[12,24,69],[73,161,203],[196,236,249]]}
];
const templateNames={meadow:'草坡',woodland:'林间',lake:'湖畔'};
const terrain=document.createElement('canvas');terrain.width=terrain.height=RES;const tc=terrain.getContext('2d');
let atlas,propAtlas,tex=[],sprites=[],photoImage=null,state,selected=null,tab='terrain',mode='paint',paint=0,prop=0,showGrid=false,hoverCell=-1;
let history=[],future=[],dirty=true,geometry,gesture=null,renderQueued=false,autosaveTimer,pendingTemplate,lastTap=0,selectionStart=null;
const clone=x=>JSON.parse(JSON.stringify(x));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296}}
function freshSeed(){return Math.floor(Math.random()*2147483647)}
function sitePoint(x,y){const d=Math.hypot(x,y);if(d>.94){x=x/d*.94;y=y/d*.94}return{x,y}}
function unusedMakeCells(seed,kind){const rand=rng(seed);return Array.from({length:32},(_,i)=>{const a=i*2.399963+rand()*.25,r=Math.sqrt((i+.5)/32)*.985;const x=Math.cos(a)*r,y=Math.sin(a)*r,z=Math.sqrt(1-r*r);let type=0;
 if(kind==='meadow'){if(x>.08&&y>.0&&x*x+(y-.25)**2<.42)type=5;else if(y>.58||x<-.76)type=4;else if(x<-.22&&y<-.05)type=2;else if(x>.46&&y<-.18)type=1;else if(Math.abs(x+y*.25)<.18)type=3}
 if(kind==='woodland'){type=1;if(x>.12)type=0;if(x>.08&&y>.35)type=5;if(y<-.45&&x<.3)type=2;if(x<-.6||y>.7)type=4;if(Math.abs(x-y*.35)<.14)type=3}
 if(kind==='lake'){type=5;if(y<-.35||x<-.65)type=0;if(x<-.3&&y<-.1)type=2;if(x>.65||y>.7)type=4;if(x>.32&&y<-.35)type=1;if(y<-.7)type=3}
 return{x,y,z,type,variant:i%2};})}
function unusedMakeState(kind='meadow',seed=freshSeed()){const configs={meadow:[[0,-.48,-.59,1],[3,.22,-.55,.88],[1,-.5,-.2,.9],[2,.57,.26,.85]],woodland:[[0,-.38,-.62,1.1],[5,.35,-.43,.95],[1,.58,-.03,.8],[6,.03,.1,.8]],lake:[[0,-.48,-.56,.92],[1,-.64,-.15,.9],[2,.53,.0,1],[6,.17,-.46,.9]]};return{format:'among-stars-planet',version:1,name:'一处有风的小世界',seed,template:kind,palette:0,cells:makeCells(seed,kind),items:configs[kind].map((v,i)=>({id:'start-'+i,type:v[0],x:v[1],y:v[2],scale:v[3],angle:0})),photo:null,originalPhoto:null,caption:'',ring:{type:'none',color:'#dec58f',angle:-18,width:18}}}
function capture(){history.push(clone(state));if(history.length>35)history.shift();future=[];syncUndo()}
function syncUndo(){$('undo').disabled=!history.length;$('redo').disabled=!future.length}
function notice(msg){$('save-status').textContent=msg}
function scheduleSave(){clearTimeout(autosaveTimer);notice('有新的布置 · 正在保存此设备草稿');autosaveTimer=setTimeout(()=>{try{localStorage.setItem(draftKey(),JSON.stringify(state));notice('草稿已保留在此设备')}catch{notice('设备空间不足，请用「保存作品」下载备份')}},350)}
function changed(rebuild=false){dirty=true;if(rebuild)geometry=null;scheduleSave();requestRender()}
function requestRender(){if(renderQueued)return;renderQueued=true;requestAnimationFrame(()=>{renderQueued=false;render()})}
function imageFrom(src){return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>resolve(im);im.onerror=()=>reject(new Error('图片未能读取'));im.src=src})}
function prepareTextures(){const c=document.createElement('canvas');c.width=c.height=512;const g=c.getContext('2d',{willReadFrequently:true});for(let i=0;i<6;i++){g.clearRect(0,0,512,512);g.drawImage(atlas,i%3*atlas.width/3,Math.floor(i/3)*atlas.height/2,atlas.width/3,atlas.height/2,0,0,512,512);tex.push(g.getImageData(0,0,512,512).data)}
 for(let i=0;i<8;i++){const c=document.createElement('canvas');c.width=c.height=440;const g=c.getContext('2d');g.drawImage(propAtlas,i%4*propAtlas.width/4,Math.floor(i/4)*propAtlas.height/2,propAtlas.width/4,propAtlas.height/2,0,0,440,440);sprites.push(c)}}
function buildGeometry(){const count=RES*RES;const ids=new Uint8Array(count),uv=new Uint32Array(count),shade=new Float32Array(count),alpha=new Uint8Array(count),seam=new Uint8Array(count);const half=RES/2;
 for(let py=0;py<RES;py++)for(let px=0;px<RES;px++){let x=(px-half)/half,y=(py-half)/half;const dist=Math.hypot(x,y),ang=Math.atan2(y,x);const edge=.986+.006*Math.sin(ang*13+.6)+.003*Math.sin(ang*31);if(dist>edge)continue;const z=Math.sqrt(Math.max(0,1-x*x-y*y));const wx=x+.011*Math.sin(y*43+x*16)+.005*Math.sin(y*97),wy=y+.012*Math.sin(x*37-y*13);let best=-10,second=-10,id=0;
 for(let i=0;i<state.cells.length;i++){const c=state.cells[i],dot=wx*c.x+wy*c.y+z*c.z;if(dot>best){second=best;best=dot;id=i}else if(dot>second)second=dot}
 const p=py*RES+px;ids[p]=id;seam[p]=(best-second)<.005?1:0;
 let u=Math.atan2(x,z)/Math.PI+.5,v=Math.asin(clamp(y,-1,1))/Math.PI+.5;const ix=clamp(Math.floor(u*510),0,511),iy=clamp(Math.floor(v*510),0,511);uv[p]=(iy*512+ix)*4;
 shade[p]=clamp(.77-.18*x-.14*y+.17*z,.4,1.07)*(.73+.27*Math.min(1,z*2.4));alpha[p]=Math.round(clamp((edge-dist)*half,0,1)*255)}
 geometry={ids,uv,shade,alpha,seam}}
function remap(rgb,type,palette){if(palette===0)return rgb;const orange=[[[114,52,31],[229,121,48],[255,205,132]],[[10,60,63],[22,113,113],[121,196,176]],[[162,135,94],[233,214,165],[255,248,222]],[[100,55,39],[180,92,57],[243,170,107]],[[52,89,103],[166,192,181],[250,239,209]],[[8,56,81],[21,135,150],[179,231,224]]],blue=[[[20,46,104],[71,120,185],[153,202,235]],[[9,20,53],[20,43,87],[67,104,147]],[[115,153,189],[210,228,234],[255,253,240]],[[26,59,107],[109,167,206],[223,240,242]],[[114,144,170],[226,233,230],[255,253,240]],[[8,27,71],[65,144,191],[173,222,241]]];const tones=(palette===1?orange:blue)[type];const lum=(rgb[0]*.25+rgb[1]*.6+rgb[2]*.15)/255,l=clamp((lum-.18)/.64,0,1),t=l<.5?Math.round(l*2*3)/3:Math.round((l-.5)*2*3)/3,a=l<.5?tones[0]:tones[1],b=l<.5?tones[1]:tones[2];return a.map((v,i)=>v+(b[i]-v)*t)}

function drawTerrain(){if(!geometry)buildGeometry();const out=tc.createImageData(RES,RES),d=out.data,{ids,uv,shade,alpha,seam}=geometry;
 for(let p=0;p<alpha.length;p++){if(!alpha[p])continue;const cell=state.cells[ids[p]],t=tex[cell.type],j=uv[p],k=p*4;const rgb=remap([t[j],t[j+1],t[j+2]],cell.type,state.palette);const brightness=shade[p]*(cell.variant?1:.94);for(let c=0;c<3;c++)d[k+c]=clamp(rgb[c]*brightness+(seam[p]?5:0),0,255);d[k+3]=alpha[p]}
 tc.putImageData(out,0,0);dirty=false}
function propGeometry(item){const z=Math.sqrt(Math.max(0,1-item.x**2-item.y**2)),size=sizes[item.type]*item.scale*(.76+.24*z);return{x:CX+item.x*R,y:CY+item.y*R,size,angle:item.angle*Math.PI/180+item.x*.15}}
function drawItem(g,item,selection){const p=propGeometry(item);g.save();g.translate(p.x,p.y);g.rotate(p.angle);g.fillStyle='#14241f42';g.beginPath();g.ellipse(0,-3,p.size*.24,p.size*.055,0,0,Math.PI*2);g.fill();
 if(item.type===7){if(photoImage){const ratio=Math.min(p.size/photoImage.width,p.size/photoImage.height),w=photoImage.width*ratio,h=photoImage.height*ratio;g.drawImage(photoImage,-w/2,-h,w,h)}}else g.drawImage(sprites[item.type],-p.size/2,-p.size*.96,p.size,p.size);if(selection){g.strokeStyle='#e6d7ac';g.lineWidth=1.7;g.setLineDash([5,5]);g.strokeRect(-p.size*.47,-p.size*.92,p.size*.94,p.size*.93);g.setLineDash([]);g.beginPath();g.arc(0,0,5,0,Math.PI*2);g.fillStyle='#e8d6a5';g.fill()}g.restore()}
function render(g=ctx,clean=false){g.clearRect(0,0,W,W);if(!tex.length)return;if(dirty)drawTerrain();const rand=rng(9847);for(let i=0;i<44;i++){const x=70+rand()*760,y=90+rand()*720;if(Math.hypot(x-CX,y-CY)<R+25)continue;g.fillStyle=i%4?'#c3b88972':'#e0c58a';g.beginPath();g.arc(x,y,rand()*1.3+.5,0,7);g.fill()}
 drawRing(g,false);g.drawImage(terrain,CX-R,CY-R,R*2,R*2);
 if(showGrid&&!clean){const grid=g.createImageData(RES,RES);for(let p=0;p<geometry.ids.length;p++){if(!geometry.alpha[p])continue;const k=p*4;if(geometry.seam[p]){grid.data[k]=236;grid.data[k+1]=226;grid.data[k+2]=196;grid.data[k+3]=125}else if(geometry.ids[p]===hoverCell){grid.data[k]=237;grid.data[k+1]=226;grid.data[k+2]=198;grid.data[k+3]=40}}const tmp=document.createElement('canvas');tmp.width=tmp.height=RES;tmp.getContext('2d').putImageData(grid,0,0);g.drawImage(tmp,CX-R,CY-R,R*2,R*2)}
 [...state.items].sort((a,b)=>a.y-b.y).forEach(item=>drawItem(g,item,!clean&&item.id===selected));drawRing(g,true);}
function point(e){const b=canvas.getBoundingClientRect();return{x:(e.clientX-b.left)/b.width*W,y:(e.clientY-b.top)/b.height*W}}
function surfacePoint(p){const x=(p.x-CX)/R,y=(p.y-CY)/R;return x*x+y*y<.98?{x,y}:null}
function cellAt(p){const x=Math.floor((p.x-CX+R)/(2*R)*RES),y=Math.floor((p.y-CY+R)/(2*R)*RES);return x>=0&&y>=0&&x<RES&&y<RES&&geometry.alpha[y*RES+x]?geometry.ids[y*RES+x]:-1}
function hitItem(p){return [...state.items].sort((a,b)=>b.y-a.y).find(item=>{const t=propGeometry(item),dx=p.x-t.x,dy=p.y-t.y,x=dx*Math.cos(t.angle)+dy*Math.sin(t.angle),y=-dx*Math.sin(t.angle)+dy*Math.cos(t.angle);return Math.abs(x)<t.size*.47&&y>-t.size*.94&&y<t.size*.04})}
function paintAt(p){const id=cellAt(p);hoverCell=id;if(id>=0&&state.cells[id].type!==paint){state.cells[id].type=paint;changed()}}
function place(type,p){if(type===7&&!state.photo){switchTab('memory');notice('先上传一张照片或透明贴纸。');return}if(state.items.length>=24){notice('这颗小星球已放下 24 件小物，可以先移走一些。');return}const pos=surfacePoint(p);if(!pos){notice('轻点星球表面，给它找个落脚的位置。');return}capture();const id='item-'+Date.now()+'-'+Math.floor(Math.random()*999);state.items.push({id,type,...sitePoint(pos.x,pos.y),scale:1,angle:0});selected=id;mode='move';setModeUI();syncSelection();changed()}
canvas.addEventListener('pointerdown',e=>{if(!geometry)return;const p=point(e);canvas.setPointerCapture?.(e.pointerId);if(mode==='paint'){if(cellAt(p)<0)return;capture();gesture={kind:'paint'};paintAt(p)}else if(mode==='place'){place(prop,p)}else{let hit=hitItem(p);if(hit&&((flowStep===3&&hit.type!==7)||(flowStep===2&&hit.type===7)))hit=null;selected=hit?.id||null;if(hit&&tab==='terrain')switchTab('objects');syncSelection();requestRender();if(hit){if(hit.type===7&&Date.now()-lastTap<400){openPhoto();lastTap=0;return}lastTap=Date.now();gesture={kind:'drag',id:hit.id,offsetX:p.x-(CX+hit.x*R),offsetY:p.y-(CY+hit.y*R),before:clone(state),moved:false}}}});
canvas.addEventListener('pointermove',e=>{const p=point(e);if(!gesture){if(showGrid&&geometry){hoverCell=cellAt(p);requestRender()}return}if(gesture.kind==='paint')paintAt(p);else{const item=state.items.find(x=>x.id===gesture.id);if(!item)return;if(!gesture.moved){history.push(gesture.before);future=[];syncUndo();gesture.moved=true}const pos=sitePoint((p.x-gesture.offsetX-CX)/R,(p.y-gesture.offsetY-CY)/R);Object.assign(item,pos);requestRender();scheduleSave()}});
function endGesture(){gesture=null}canvas.addEventListener('pointerup',endGesture);canvas.addEventListener('pointercancel',endGesture);
function setModeUI(){$('move').setAttribute('aria-pressed',String(mode==='move'));$('mode-note').textContent=mode==='paint'?`正在铺${materials[paint]} · 点按或拖动地表。`:mode==='place'?`把${objects[prop]}放在哪里？轻点星球表面。`:'拖动小物件调整位置，点两下贴纸查看照片。';document.querySelectorAll('[data-material]').forEach(b=>b.classList.toggle('active',mode==='paint'&&+b.dataset.material===paint));document.querySelectorAll('[data-object]').forEach(b=>b.classList.toggle('active',mode==='place'&&+b.dataset.object===prop))}
function switchTab(next){tab=next;document.querySelectorAll('[data-tab]').forEach(b=>{const on=b.dataset.tab===next;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on)});['terrain','objects','rings','memory'].forEach(k=>$('panel-'+k).hidden=k!==next);mode=next==='terrain'?'paint':'move';setModeUI();syncSelection()}
function syncSelection(){const item=state.items.find(i=>i.id===selected);$('selection-controls').hidden=!item;if(item)$('panel-'+(flowStep===3?'memory':'objects')).append($('selection-controls'));if(item){$('selected-name').textContent='正在布置 · '+objects[item.type];$('object-size').value=Math.round(item.scale*100);$('object-angle').value=item.angle}}
function syncUI(){syncRing();syncMaterials();$('world-name').value=state.name;$('photo-caption').value=state.caption;document.querySelectorAll('[data-palette]').forEach(b=>b.classList.toggle('active',+b.dataset.palette===state.palette));const pv=$('photo-preview');pv.replaceChildren();if(state.photo){const im=document.createElement('img');im.src=state.photo;im.alt='已上传的照片';pv.append(im)}else{pv.append('＋');const small=document.createElement('small');small.textContent='选择一张照片';pv.append(small)}syncSelection();syncUndo();setModeUI()}
async function restore(next){state=clone(next);selected=null;geometry=null;dirty=true;photoImage=state.photo?await imageFrom(state.photo):null;syncUI();scheduleSave();requestRender()}
$('undo').onclick=async()=>{if(!history.length)return;future.push(clone(state));await restore(history.pop())};$('redo').onclick=async()=>{if(!future.length)return;history.push(clone(state));await restore(future.pop())};
$('grid').onclick=()=>{showGrid=!showGrid;$('grid').setAttribute('aria-pressed',showGrid);requestRender()};$('move').onclick=()=>{mode=mode==='move'&&tab==='terrain'?'paint':'move';setModeUI()};
for(const [key,name] of Object.entries(templateNames)){const b=document.createElement('button');b.dataset.template=key;b.innerHTML=`<span class="template-orb"></span>${name}`;b.onclick=()=>{pendingTemplate=key;$('template-dialog').showModal()};$('templates').append(b)}
$('cancel-template').onclick=()=>$('template-dialog').close();$('confirm-template').onclick=()=>{capture();const next=makeState(pendingTemplate);next.items.push(...state.items.filter(i=>i.type===7).map(clone));next.photo=state.photo;next.originalPhoto=state.originalPhoto||state.photo;next.ring=clone(state.ring);next.caption=state.caption;next.name=state.name;next.palette=state.palette;restore(next);$('template-dialog').close()};
materials.forEach((name,i)=>{const b=document.createElement('button');b.dataset.material=i;const sw=document.createElement('div');sw.className='material-swatch';sw.style.backgroundPosition=`${i%3*50}% ${Math.floor(i/3)*100}%`;b.append(sw,name);b.onclick=()=>{paint=i;mode='paint';selected=null;setModeUI();syncSelection();requestRender();focusCanvas()};$('materials').append(b)});
schemes.forEach((scheme,i)=>{const b=document.createElement('button');b.dataset.palette=i;const colors=document.createElement('span');colors.className='color-swatches';scheme.chips.forEach(color=>{const s=document.createElement('i');s.style.background=color;colors.append(s)});b.append(colors,scheme.name);b.onclick=()=>{if(state.palette===i)return;capture();state.palette=i;syncUI();changed()};$('palettes').append(b)});
objects.forEach((name,i)=>{if(i===7)return;const b=document.createElement('button');b.dataset.object=i;const sw=document.createElement('div');sw.className='object-swatch';sw.style.backgroundPosition=`${i%4*100/3}% ${Math.floor(i/4)*100}%`;if(i===7){sw.style.backgroundImage='none';sw.textContent='＋';sw.classList.add('sticker-slot');}b.append(sw,name);b.onclick=()=>{if(i===7&&!state.photo){switchTab('memory');return}prop=i;mode='place';setModeUI();focusCanvas()};$('objects').append(b)});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));
$('regenerate').onclick=()=>{capture();state.seed=freshSeed();state.cells=makeCells(state.seed,state.template);changed(true)};
for(const [id,key,factor] of [['object-size','scale',.01],['object-angle','angle',1]]){const el=$(id);el.addEventListener('input',()=>{const item=state.items.find(i=>i.id===selected);if(!item)return;if(!selectionStart){capture();selectionStart=true}item[key]=Number(el.value)*factor;scheduleSave();requestRender()});el.addEventListener('change',()=>selectionStart=null)}
$('delete-object').onclick=()=>{if(!selected)return;capture();state.items=state.items.filter(i=>i.id!==selected);selected=null;syncSelection();changed()};
document.querySelectorAll('[data-nudge]').forEach(b=>b.onclick=()=>{const item=state.items.find(i=>i.id===selected);if(!item)return;capture();const [x,y]=b.dataset.nudge.split(',').map(Number);Object.assign(item,sitePoint(item.x+x/R,item.y+y/R));changed()});
$('world-name').addEventListener('change',()=>{capture();state.name=$('world-name').value.trim()||'一处有风的小世界';syncUI();scheduleSave()});
$('photo-caption').addEventListener('change',()=>{capture();state.caption=$('photo-caption').value;scheduleSave()});
$('photo-input').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{const original=await PetStickers.read(f),sticker=await PetStickers.outline(original);capture();state.originalPhoto=original;state.photo=sticker;photoImage=await imageFrom(sticker);if(!state.items.some(i=>i.type===7)){state.items.push({id:'pet-'+Date.now(),type:7,x:0,y:-.25,scale:1,angle:-4})}selected=state.items.find(i=>i.type===7).id;syncUI();changed();$('sticker-status').textContent='照片已变成白边贴纸。需要去掉背景时，点「自动抠出宠物」。'}catch(err){notice(err.message)}finally{e.target.value=''}};
$('cutout-photo').onclick=async()=>{if(!state.originalPhoto&&!state.photo){notice('先上传一张照片。');return}const original=state.originalPhoto||state.photo;const b=$('cutout-photo');b.disabled=true;try{const result=await PetStickers.cutout(original,t=>$('sticker-status').textContent=t);if((state.originalPhoto||state.photo)!==original)return;capture();state.originalPhoto=original;state.photo=result;photoImage=await imageFrom(result);syncUI();changed();$('sticker-status').textContent='贴纸做好了，可以放到星球上。'}catch(err){$('sticker-status').textContent=err.message}finally{b.disabled=false}};
$('crop-photo').onclick=async()=>{if(!state.originalPhoto&&!state.photo){notice('先上传照片。');return}const result=await PetStickers.crop(state.originalPhoto||state.photo);if(!result)return;capture();state.photo=result;photoImage=await imageFrom(result);syncUI();changed()};
$('restore-photo').onclick=async()=>{if(!state.originalPhoto)return;capture();state.photo=await PetStickers.outline(state.originalPhoto);photoImage=await imageFrom(state.photo);syncUI();changed();$('sticker-status').textContent='已恢复原图贴纸。'};
$('place-photo').onclick=()=>{prop=7;mode='place';setModeUI();focusCanvas()};
function openPhoto(){if(!state.photo){notice('先在「记忆」里选择一张照片。');switchTab('memory');return}$('large-photo').src=state.photo;$('large-caption').textContent=state.caption||'一个留下来的瞬间。';$('photo-dialog').showModal()}
$('view-photo').onclick=openPhoto;
$('close-photo').onclick=()=>$('photo-dialog').close();$('photo-dialog').addEventListener('click',e=>{if(e.target===$('photo-dialog'))$('photo-dialog').close()});
function download(blob,name){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
const safeName=()=>state.name.replace(/[<>:"/\\|?*]/g,'').slice(0,24)||'我的星球';
$('save-project').onclick=()=>{download(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),safeName()+'.planet.json');scheduleSave();notice('已下载作品文件，下次可用「打开作品」继续布置。')};
$('export-image').onclick=()=>{const c=document.createElement('canvas');c.width=1200;c.height=1440;const g=c.getContext('2d');g.fillStyle='#101e2b';g.fillRect(0,0,1200,1440);g.save();g.translate(0,70);g.scale(1200/900,1200/900);const layer=document.createElement('canvas');layer.width=layer.height=900;render(layer.getContext('2d'),true);g.drawImage(layer,0,0);g.restore();g.textAlign='center';g.fillStyle='#e8dfc4';g.font='32px serif';g.fillText(state.name,600,1290,1050);g.font='16px serif';g.fillStyle='#9ca695';g.fillText('群星之间 · AMONG THE STARS',600,1345);c.toBlob(blob=>{if(blob){download(blob,safeName()+'.png');notice('已导出星球图片。')}else notice('图片导出失败，请重试。')},'image/png')};
function validate(s){if(!s||s.format!=='among-stars-planet'||s.version!==1||!Object.hasOwn(templateNames,s.template)||!Number.isInteger(s.seed)||!Number.isInteger(s.palette)||s.palette<0||s.palette>2||!Array.isArray(s.cells)||s.cells.length!==32||!Array.isArray(s.items)||s.items.length>24)throw Error('这不是有效的星球作品文件。');for(const c of s.cells){if(![c.x,c.y,c.z].every(Number.isFinite)||Math.abs(c.x)>1||Math.abs(c.y)>1||c.z<0||c.z>1||!Number.isInteger(c.type)||c.type<0||c.type>5||![0,1].includes(c.variant))throw Error('地表数据不完整。')}const ids=new Set();for(const i of s.items){if(typeof i.id!=='string'||ids.has(i.id)||!Number.isInteger(i.type)||i.type<0||i.type>7||![i.x,i.y,i.scale,i.angle].every(Number.isFinite)||Math.hypot(i.x,i.y)>.951||i.scale<.65||i.scale>1.45||Math.abs(i.angle)>25)throw Error('物件数据不完整。');ids.add(i.id)}if(typeof s.name!=='string'||s.name.length>24||typeof s.caption!=='string'||s.caption.length>160||(s.photo!==null&&(typeof s.photo!=='string'||!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(s.photo)||s.photo.length>4000000)))throw Error('照片或文字格式不正确。');s.ring=s.ring||{type:'none',color:'#dec58f',angle:-18,width:18};if(!['none','line','crayon','dust'].includes(s.ring.type)||!/^#[a-f0-9]{6}$/i.test(s.ring.color)||!Number.isFinite(s.ring.angle)||Math.abs(s.ring.angle)>45||!Number.isFinite(s.ring.width)||s.ring.width<5||s.ring.width>38)throw Error('星环数据不完整。');if(s.originalPhoto!=null&&(typeof s.originalPhoto!=='string'||!/^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(s.originalPhoto)||s.originalPhoto.length>4000000))throw Error('原图格式不正确。');return s}
$('open-project').onclick=()=>$('project-input').click();$('project-input').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>10000000)throw Error('作品文件过大。');const next=validate(JSON.parse(await f.text()));if(next.photo)await imageFrom(next.photo);capture();await restore(next);notice('作品已打开，可以继续布置。')}catch(err){notice(err.message||'无法打开作品。')}finally{e.target.value=''}};
window.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(e.target.tagName))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();(e.shiftKey?$('redo'):$('undo')).click()}if(e.key==='Delete')$('delete-object').click()});
async function start(){document.querySelectorAll('button,input,textarea').forEach(el=>el.disabled=true);try{await CollagePlanet.ready;[atlas,propAtlas]=await Promise.all([imageFrom('./assets/studio-terrain.webp'),imageFrom('./assets/studio-objects.webp')]);prepareTextures();try{const saved=JSON.parse(localStorage.getItem(draftKey()));const record=readPet();state=record?.planet?validate(record.planet):saved?validate(saved):record?CollagePlanet.fromRecord(record):makeState();if(record?.planet){state.photo=record.avatar||state.photo;state.originalPhoto=record.originalPhoto||state.photo}if(record&&!record.planet){state.name=(record.name+'的小世界').slice(0,24);state.originalPhoto=record.originalPhoto||record.avatar||null;state.photo=record.avatar||null;state.caption=(record.words||'').slice(0,160)}}catch{state=makeState()}if(state.photo)try{photoImage=await imageFrom(state.photo)}catch{state.photo=null}document.querySelectorAll('button,input,textarea').forEach(el=>el.disabled=false);if(creating&&creation)state.name=(creation.name+'的小世界').slice(0,24);syncUI();setFlowStep(flowStep);render();$('loading').hidden=true;notice('布置会自动留在此设备')}catch{const el=$('loading');el.textContent='素材未加载完成，点这里重试。';el.style.zIndex=5;el.style.cursor='pointer';el.onclick=()=>location.reload()}}
function focusCanvas(){}
function syncMaterials(){if(!tex.length||!state)return;document.querySelectorAll('[data-material]').forEach((b,i)=>{const c=document.createElement('canvas');c.width=c.height=72;const g=c.getContext('2d'),image=g.createImageData(72,72);for(let y=0;y<72;y++)for(let x=0;x<72;x++){const j=(Math.floor(y/72*512)*512+Math.floor(x/72*512))*4,k=(y*72+x)*4,rgb=remap([tex[i][j],tex[i][j+1],tex[i][j+2]],i,state.palette);image.data.set([...rgb,255],k)}g.putImageData(image,0,0);const sw=b.querySelector('.material-swatch');sw.style.backgroundImage=`url(${c.toDataURL()})`;sw.style.backgroundSize='cover';sw.style.backgroundPosition='center'})}
function syncRing(){const r=state.ring||{type:'none',color:'#dec58f',angle:-18,width:18};state.ring=r;document.querySelectorAll('[data-ring]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.ring===r.type)));$('ring-controls').hidden=r.type==='none';$('ring-color').value=r.color;$('ring-angle').value=r.angle;$('ring-width').value=r.width}
for(const [type,name] of [['none','无星环'],['line','手绘细环'],['crayon','蜡笔宽环'],['dust','星尘环']]){const b=document.createElement('button');b.dataset.ring=type;b.textContent=name;b.onclick=()=>{capture();state.ring.type=type;syncRing();changed();focusCanvas()};$('rings').append(b)}
for(const [id,key] of [['ring-color','color'],['ring-angle','angle'],['ring-width','width']]){$(id).addEventListener('input',()=>{if(!selectionStart){capture();selectionStart=true}state.ring[key]=key==='color'?$(id).value:Number($(id).value);changed()});$(id).addEventListener('change',()=>selectionStart=false)}
function drawRing(g,front){const r=state.ring;if(!r||r.type==='none')return;g.save();g.translate(CX,CY);g.rotate(r.angle*Math.PI/180);const rand=rng(state.seed+82);g.strokeStyle=r.color;g.fillStyle=r.color;const start=front?0:Math.PI,end=start+Math.PI;
 if(r.type==='dust'){for(let i=0;i<520;i++){const t=start+rand()*Math.PI,rad=R*1.25+(rand()-.5)*r.width*2;g.globalAlpha=.25+rand()*.65;g.beginPath();g.arc(Math.cos(t)*rad,Math.sin(t)*rad*.32,.5+rand()*2.1,0,7);g.fill()}}
 else{const n=r.type==='line'?3:22;for(let i=0;i<n;i++){const rad=R*1.2+i/(n-1)*r.width*1.8;g.globalAlpha=r.type==='line'?.75:.25+rand()*.3;g.lineWidth=r.type==='line'?1.5:2.7;g.beginPath();for(let j=0;j<=150;j++){const t=start+(end-start)*j/150,rr=rad+Math.sin(t*31+i)*1.2+(rand()-.5)*1.5;const x=Math.cos(t)*rr,y=Math.sin(t)*rr*.32;j?g.lineTo(x,y):g.moveTo(x,y)}g.stroke()}}g.restore()}
function readPet(){try{return JSON.parse(localStorage.getItem('among-the-stars-memorials-v1')||'[]').find(r=>r.id===petId)}catch{return null}}
function saveToPet(){if(!petId)return;const records=JSON.parse(localStorage.getItem('among-the-stars-memorials-v1')||'[]'),record=records.find(r=>r.id===petId);if(!record)return;const c=document.createElement('canvas');c.width=c.height=480;CollagePlanet.draw(state,c,photoImage);record.planet={...clone(state),photo:null,originalPhoto:null};record.planetPreview=c.toDataURL('image/webp',.88);record.avatar=state.photo||'';record.originalPhoto=state.originalPhoto||state.photo||'';localStorage.setItem('among-the-stars-memorials-v1',JSON.stringify(records))}
window.addEventListener('pagehide',()=>{if(!state)return;clearTimeout(autosaveTimer);try{localStorage.setItem(draftKey(),JSON.stringify(state))}catch{}});

function draftKey(){return petId?STORE+':'+petId:creating?STORE+':creation':STORE}
function setFlowStep(step){flowStep=step;document.body.dataset.step=String(step);$('flow-title').textContent=step===2?'布置星球':'添加宠物贴纸';$('flow-count').textContent=creating?step+' / 3':'编辑星球';$('flow-next').textContent=step===2&&creating?'下一步 · 添加贴纸':creating?'完成，收进观星手册':params.get('return')==='world'?'保存修改，回到星球':'保存修改，返回手册';$('flow-skip').hidden=!creating||step!==3;document.querySelector('.tabs').hidden=step===3;selected=null;switchTab(step===3?'memory':'terrain');localStorage.setItem('among-stars-creation-step',String(step));$('flow-back').textContent=step===3?'← 布置星球':'← 返回';}
$('flow-back').onclick=()=>{if(flowStep===3&&creating){setFlowStep(2);return}location.href=creating?'./?view=create':petId?'./?pet='+encodeURIComponent(petId)+'&view='+(params.get('return')==='world'?'world':'journal'):'./'};
function complete(){try{
 clearTimeout(autosaveTimer);
 if(creating&&!creation?.name)throw Error('请先填写TA的名字。');
 const records=JSON.parse(localStorage.getItem('among-the-stars-memorials-v1')||'[]');const id=petId||creation?.id;
 if(!id)throw Error('请从「创建星球」或自己的星球进入。');
 const old=records.find(r=>r.id===id);if(!old&&!creating)throw Error('未找到这颗星球，请返回手册。');
 const c=document.createElement('canvas');c.width=c.height=480;CollagePlanet.draw(state,c,photoImage);
 const record={...(old||creation),planet:{...clone(state),photo:null,originalPhoto:null},planetPreview:c.toDataURL('image/webp',.88),avatar:state.photo||'',originalPhoto:state.originalPhoto||state.photo||''};
 const next=old?records.map(r=>r.id===id?record:r):[...records,record];
 localStorage.setItem('among-the-stars-memorials-v1',JSON.stringify(next));petId=id;
 if(creating){localStorage.removeItem('among-stars-creation-v2');localStorage.removeItem(STORE+':creation');localStorage.removeItem('among-stars-creation-step')}
 location.href='./?pet='+encodeURIComponent(id)+'&view='+(!creating&&params.get('return')==='world'?'world':'journal');
 }catch(err){notice(err.message||'暂时无法保存，请保留此页并重试。')}}
$('flow-next').onclick=()=>{if(creating&&flowStep===2){setFlowStep(3);return}complete()};
$('flow-skip').onclick=()=>{state.photo=null;state.originalPhoto=null;photoImage=null;state.items=state.items.filter(i=>i.type!==7);complete()};
$('remove-photo').onclick=()=>{capture();state.photo=null;state.originalPhoto=null;photoImage=null;state.items=state.items.filter(i=>i.type!==7);selected=null;syncUI();changed()};

$('open-backup').onclick=()=>$('open-project').click();$('backup-project').onclick=()=>$('save-project').click();$('backup-image').onclick=()=>$('export-image').click();
start();
})();
